#version 450
#extension GL_GOOGLE_include_directive : require

#include "../../common/scene_rt.glsl"

layout(std140, set = 0, binding = 0) uniform UniformBuffer {
    GlassUniformsData uniforms;
};

layout(set = 0, binding = 10, rgba32f) readonly uniform image2DArray cascade0Tex;
layout(set = 0, binding = 4, rgba32f) uniform image2D irradianceAtlas;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#define CASCADE_RAYS_THIS 16u

#include "../../common/cascade_integrate_main.glsl"
