#version 430 core
#extension GL_GOOGLE_include_directive : enable

#include "../../common/scene_rt.glsl"

layout(std140, binding = 0) uniform UniformBuffer {
    GlassUniformsData uniforms;
};

layout(std430, binding = 1) readonly buffer BVHBuffer {
    GPUBVHNode bvhNodes[];
};

layout(std430, binding = 2) readonly buffer TriBuffer {
    GPUTriangle triangles[];
};

#include "../../common/scene_intersect.glsl"
#include "../../common/cascade_common.glsl"

layout(binding = 12, rgba32f) writeonly uniform image2DArray outCascade;
layout(binding = 13, rgba32f) readonly uniform image2DArray upperCascade;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

#define CASCADE_PROBES_THIS 16u
#define CASCADE_RAYS_THIS 256u
#define CASCADE_TMIN 0.80
#define CASCADE_TMAX 2.50
#define CASCADE_HAS_UPPER 1
#define CASCADE_PROBES_UPPER 8u
#define CASCADE_RAYS_UPPER 1024u

#include "../../common/cascade_gather_main.glsl"
